# These are supported funding model platforms

github: [Bill ManChild, Mark the mime, Dr Jeff Evil]
patreon: brokabilly 
open_collective: greedisgood
ko_fi: givemeallthedough
tidelift: ilovemoney
community_bridge: cashgrab69
liberapay: liberafree
issuehunt: nofingway
lfx_crowdfunding: whereiswaldo
polar: opposites
buy_me_a_coffee: beerorbooze
thanks_dev: devsdontcare
custom: ['tisfreemydude.party']
